[build]
  command = "npm run functions"
  publish = "public"
  functions = "functions"

[dev]
  publish = "public"
  functions = "functions"

[template.environment]
  STRIPE_PUBLISHABLE_KEY = "pk_test_6k2VkzoyMAV03Ka1OMPSQzlk00kvMUTm0N"
  STRIPE_SECRET_KEY = "sk_test_09zZ4Qwl9cmu2vBgrRof0PQN00NC9RpgRU"
